#!/usr/bin/env node

"use strict";

process.title = 'vhm2nvhm';

var cli = require('cli')
,exec = require('child_process').exec
,fs = require('fs')
,dir = __dirname;

cli.parse({
	apacheDir: [
		'apache-dir'
		,'Directory with Apache\'s configuration'
		,'path'
		,'/etc/apache2'
	]
	,nginxDir: [
		'conf-dir'
		,'Directory with nginx\'s configuration'
		,'path'
		,'/etc/nginx'
	]
	,reverse: [
		'reverse'
		,'If true the convertion is from nvhm format to vhm format'
		,'boolean'
		,false
	]
});

cli.main(function(args, options)
{
	var reverse = options.reverse
	,Converter = require(dir + '/converters/' + (reverse ? 'nvhm2vhm' : 'vhm2nvhm'))
	,converter = new Converter(options.apacheDir, options.nginxDir);

	converter.processAll();

	exec('/etc/init.d/' + (reverse ? 'apache2' : 'nginx') + ' restart', function()
	{
		cli.ok('Everything done');
	})
});
